### ISSUE TITLE
NullPointerException in FlatScrollBarUI

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#158]
I came across this NPE in my application's log, an hour after I finished with my session. I don't have much information besides the stack trace. I was mainly playing around with a JTree in a JScrollPane but I wouldn't be able to tell you exactly what caused the Exception. The last theme I was using is "Arc Dark" although this may not be the one that was being used when this Exception happens.

I haven't been able to replicate it since. I'll update with any more details if I come across it.

```
ERROR | jvm 1    | 2020/08/11 16:23:34 | java.lang.NullPointerException
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.util.HSLColor.fromRGB(HSLColor.java:264)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.util.ColorFunctions.applyFunctions(ColorFunctions.java:29)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.util.DerivedColor.derive(DerivedColor.java:47)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.ui.FlatUIUtils.deriveColor(FlatUIUtils.java:214)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.ui.FlatScrollBarUI.getTrackColor(FlatScrollBarUI.java:285)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.ui.FlatScrollBarUI.paintTrack(FlatScrollBarUI.java:238)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.paint(BasicScrollBarUI.java:507)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at com.formdev.flatlaf.ui.FlatScrollBarUI.paint(FlatScrollBarUI.java:233)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at prod1.swing.GlobalHotKeyManager.dispatchEvent(GlobalHotKeyManager.java:79)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
ERROR | jvm 1    | 2020/08/11 16:23:34 | 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DevCharly** [comment]
This happens in the Solarized themes when moving mouse over scrollbars.

Fixed in commit 5a27d03faa25413b4078c87764fe1126a88dac52 and released in FlatLaf 0.40
