### ISSUE TITLE
How to compile and run the Theme Editor

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#160]
Hey,

I was wondering whether it's able to look at the current state of the theme editor. But I can't quite figure out how to launch it.

**Comment by DevCharly** [comment]
The theme editor is still very limited and kind of experiment...

It is a text editor for FlatLaf properties files with syntax highlighting, auto-complete, mark occurrences, color preview, etc.
(not sure whether this is the right direction; maybe a GUI that allows configuring basic/common settings would be more useful for most developers and probably much simpler to use)

Use gradle (or any IDE with gradle support) to compile sub-project `flatlaf-theme-editor`.
The main class is `com.formdev.flatlaf.themeeditor.FlatThemeFileEditor`.
First parameter is the name of the properties file to edit.
Subsequent parameters are base properties files, which are basically used to grab base values for derived colors.

E.g. to edit core `FlatLightLaf.properties` pass following parameters:
~~~
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
~~~

This is what it currently looks like:

![image](https://user-images.githubusercontent.com/5604048/90004529-198b8300-dc96-11ea-8be3-ea8dae6b38c6.png)

Auto-complete demo:

![theme-editor-auto-complete](https://user-images.githubusercontent.com/5604048/90006123-9ddf0580-dc98-11ea-921a-c2dd6eaa5ffb.gif)

`Ctrl+S` works to save the changes.
It is not possible to open another file.
There is no color chooser.

**Comment by Bios-Marcel** [comment]
Maybe it'd be nice to add a gradle task that just allows running. Or maybe even creating a fat-jar task.

When i try this, I jsut get this:

```
PS D:\repos\FlatLaf\flatlaf-theme-editor\build\libs> java -cp .\flatlaf-theme-editor-0.41-SNAPSHOT.jar com.formdev.flatlaf.themeeditor.FlatThemeFileEditor
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/formdev/flatlaf/FlatLightLaf
        at com.formdev.flatlaf.themeeditor.FlatThemeFileEditor.lambda$main$1(FlatThemeFileEditor.java:52)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.formdev.flatlaf.FlatLightLaf
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 15 more
```

What exactly am I supposed to do to compile it? I did `gradle jar` and used the jar from build\libs\ and manually added the Main-Class to the manifest.

**Comment by DevCharly** [comment]
Just changed the gradle jar task to create a fat jar and also added the main class to the manifest.

Now it is possible to launch with:
`java -jar flatlaf-theme-editor-0.41-SNAPSHOT.jar myTheme.properties ...`

**Comment by Bios-Marcel** [comment]
Cool, I'll check it out tomorrow :)

**Comment by Bios-Marcel** [comment]
Works 👍 

So, I was wondering. The intellij themes are JSON, right? How come that the non-intellij ones are .properties files? Are the JSON ones the official format that IntelliJ uses and did you just happen to start out with .properties?

**Comment by DevCharly** [comment]
The properties files are the core format used in FlatLaf to specify nearly all kind of UI defaults (colors, border, icons, insets, dimension, etc). IntelliJ IDEA also uses properties files for its core themes (see [darcula.properties](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ide/ui/laf/darcula/darcula.properties)).

In most other LaFs this kind of UI defaults are defined in Java code (e.g. classes `com.sun.java.swing.plaf.windows.WindowsLookAndFeel` or `javax.swing.plaf.metal.MetalLookAndFeel`).

The JSON files are loaded after the properties files have been applied and allow overwriting UI defaults.
So when loading JSON themes in FlatLaf they are always based on FlatLaf IntelliJ/Darcula themes.
This is the same as in IntelliJ IDEA. JSON themes do not contain complete set of UI values.

Don't know why JetBrains did choose JSON for this. They already had properties format in Darcula LaF.
Maybe IDEA has better editor support (or inspections) for JSON than for properties?

**Comment by Msharifiuk** [comment]
Hi
I have an issue like same as happened you
When I try and log in to the application I get a “can't load javax.swing.plaf.metal.MetalLookAndFeel” error and I can’t log in.

have you any idea?
