### ISSUE TITLE
Issues with JCalendar (Error when flatlaf is added on netbeans libraries

### ISSUE THREAD

**Issue by emmanbarrameda** [JFormDesigner/FlatLaf#194]
java.lang.NullPointerException
	at com.formdev.flatlaf.ui.FlatUIUtils.addInsets(FlatUIUtils.java:85)
	at com.formdev.flatlaf.ui.FlatScrollBarUI.getMinimumThumbSize(FlatScrollBarUI.java:287)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutVScrollbar(BasicScrollBarUI.java:691)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(BasicScrollBarUI.java:866)
	at javax.swing.plaf.basic.BasicScrollBarUI$ModelListener.stateChanged(BasicScrollBarUI.java:1054)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
	at javax.swing.JScrollBar.setValues(JScrollBar.java:623)
	at javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(BasicScrollPaneUI.java:285)
	at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1034)
	at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
	at javax.swing.JViewport.setViewPosition(JViewport.java:1125)
	at javax.swing.JViewport.scrollRectToVisible(JViewport.java:436)
	at javax.swing.JComponent.scrollRectToVisible(JComponent.java:3111)
	at javax.swing.JList.ensureIndexIsVisible(JList.java:1149)
	at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1180)
	at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:63)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1008)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at com.toedter.calendar.JMonthChooser.setMonth(Unknown Source)
	at com.toedter.calendar.JMonthChooser.setMonth(Unknown Source)
	at com.toedter.calendar.JMonthChooser.<init>(Unknown Source)
	at com.toedter.calendar.JCalendar.<init>(Unknown Source)
	at com.toedter.calendar.JCalendar.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.netbeans.modules.form.CreationFactory.createDefaultInstance(CreationFactory.java:155)
	at org.netbeans.modules.form.RADComponent.createBeanInstance(RADComponent.java:227)
	at org.netbeans.modules.form.RADComponent.initInstance(RADComponent.java:166)
	at org.netbeans.modules.form.MetaComponentCreator.initComponentInstance(MetaComponentCreator.java:1495)
	at org.netbeans.modules.form.MetaComponentCreator.createVisualComponent(MetaComponentCreator.java:962)
	at org.netbeans.modules.form.MetaComponentCreator.access$300(MetaComponentCreator.java:54)
	at org.netbeans.modules.form.MetaComponentCreator$2.run(MetaComponentCreator.java:257)
	at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:268)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:115)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:75)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:225)
	at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:251)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:254)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:273)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.init(HandleLayer.java:3344)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.<init>(HandleLayer.java:3336)
	at org.netbeans.modules.form.HandleLayer$NewComponentDropListener.dragEnter(HandleLayer.java:3633)
	at java.awt.dnd.DropTarget.dragEnter(DropTarget.java:358)
	at sun.awt.dnd.SunDropTargetContextPeer.processEnterMessage(SunDropTargetContextPeer.java:331)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEnterEvent(SunDropTargetContextPeer.java:799)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:767)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4676)
	at java.awt.LightweightDispatcher.trackDropTargetEnterExit(Container.java:4625)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4638)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4591)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DevCharly** [comment]
Looking at the stack, it seems that you are running NetBeans and use the NetBeans GUI builder, right?
And you add a JCalendar component to a form and the exception occurs, right?

Are you running NetBeans on FlatLaf look and feel?
What NetBeans and FlatLaf versions do you use?

I tried NetBeans GUI builder but was not yet able to reproduce the issue...

**Comment by DevCharly** [comment]
@emmanbarrameda do you have any additional information for me?

**Comment by emmanbarrameda** [comment]
I use Netbeans Apache 12.0
NetBeans GUI builder

I use the Latest Version of FlatLaf

I use the Latest Version of JCalendar

and the issue happened.

**Comment by DevCharly** [comment]
Finally was able to reproduce this issue 😃 

NetBeans 12 comes with bundled FlatLaf 0.31, which is also used in NB GUI builder for core components (e.g. `JScrollBar`).
On the other hand, when using a custom component (e.g. `JCalendar`) from a NB Library (menu `Tools > Libraries`), the NB GUI builder also looks into NB Libraries for UI delegates (e.g. `FlatScrollBarUI`).

The problem now is that FlatLaf 0.43 in NB Libraries is newer than NB bundled FlatLaf 0.31 and uses a value for `UIManager.get()` that does not exist in NB. Therefore the NPE.

I've fixed this in commit 539737d1c5a2b36ac64f94b59843770dbe17336b.
Use the latest snapshot (https://github.com/JFormDesigner/FlatLaf#snapshots) until the next version is release.

**This is only a problem in NetBeans GUI builder.** Applications are not affected.
