### ISSUE TITLE
IndexOutOfBoundsException when using TABBED_PANE_TAB_CLOSE_TOOLTIPTEXT with TABBED_PANE_TAB_CLOSE_CALLBACK

### ISSUE THREAD

**Issue by ParkerTenBroeck** [JFormDesigner/FlatLaf#235]
When using TABBED_PANE_TAB_CLOSE_TOOLTIPTEXT with TABBED_PANE_TAB_CLOSE_CALLBACK The GUI freezes and will output IndexOutOfBoundsExceptions whenever it tries to update

```java
myTabbedPane.putClientProperty( "JTabbedPane.tabClosable", true );
myTabbedPane.putClientProperty("JTabbedPane.tabCloseToolTipText", "Close");
myTabbedPane.putClientProperty( "JTabbedPane.tabCloseCallback",
    (java.util.function.BiConsumer<JTabbedPane, Integer>) (tabbedPane, tabIndex) -> {
        // close tab here
        tabbedPane.removeTabAt( tabIndex );
    } );
```

```java
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at javax.swing.JTabbedPane.setToolTipTextAt(JTabbedPane.java:1426)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.restoreTabToolTip(FlatTabbedPaneUI.java:2191)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.updateRollover(FlatTabbedPaneUI.java:2172)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.mouseExited(FlatTabbedPaneUI.java:2132)
	at java.awt.AWTEventMulticaster.mouseExited(AWTEventMulticaster.java:309)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4668)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4654)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4505)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DevCharly** [comment]
Many thanks for reporting this issue.
Fixed in main branch.
