### ISSUE TITLE
ServiceConfigurationError (NbFlatDefaultsAddon not a subtype) when initializing in NetBeans RCP application

### ISSUE THREAD

**Issue by JoachimRohde** [JFormDesigner/FlatLaf#255]
I have an NetBeans RCP application that is based on NetBeans 12.2. Used Java version is 11.0.9.1. I wanted to give FlatLaF (1.0-rc3) a try but as soon as `FlatDarkLaf.install();` is called I get the following output in the console:

```
16:40:51.565 INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'MainTopComponent'. Reason: null
Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
<settings version="1.0">
  <instance class="com.myproject.myprojectmodule.windows.MainTopComponent"/>
</settings>
Class: class com.myproject.myprojectmodule.windows.MainTopComponent
Source: MultiFileObject@1db834[Windows2Local/Components/MainTopComponent.settings]
Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
<settings version="1.0">
  <instance class="com.myproject.myprojectmodule.windows.MainTopComponent"/>
</settings>
Class: class com.myproject.myprojectmodule.windows.MainTopComponent
Source: MultiFileObject@1db834[Windows2Local/Components/MainTopComponent.settings]
Caused: java.util.ServiceConfigurationError: com.formdev.flatlaf.FlatDefaultsAddon: org.netbeans.swing.laf.flatlaf.NbFlatDefaultsAddon not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1266)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:406)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at com.myproject.myprojectmodule.windows.MainTopComponent.<init>(MainTopComponent.java:120)
```
	
How can I disable the search for addon .properties in FlatLaF or configure it in a way so that it's not causing any exception?

**Comment by DevCharly** [comment]
I think the problem is that you have two different FlatLaf versions in your application:
- 1.0-rc3 (added by you)
- 0.31 in NetBeans module `org.netbeans.libs.flatlaf`

Please try without 1.0-rc3.

BTW NetBeans 12.3 beta 2 comes with FlatLaf 1.0-rc2.

**Comment by DevCharly** [comment]
Some more information: If you have two FlatLaf versions loaded in two different classloaders (each NB module has its own CL), then there two different independent `FlatDefaultsAddon` classes. The `ServiceLoader` checks whether the found service class is assignable to the expected class (from 1.0-rc3), but the service uses the class from 0.31.

**Comment by JoachimRohde** [comment]
I tried to use 0.31:
```
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>0.31</version>
        </dependency>        
```
which did not work. 

But using

```
<dependency>
    <groupId>org.netbeans.api</groupId>
    <artifactId>org-netbeans-libs-flatlaf</artifactId>
    <version>RELEASE122</version>
</dependency>

```
did the trick. Thanks for the help.
