### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0 when setting a JTabbedPane title

### ISSUE THREAD

**Issue by lgvr123** [JFormDesigner/FlatLaf#271]
This code generates a ```java.lang.ArrayIndexOutOfBoundsException: 0 >= 0```
```
 void setTileFor(clResultsPanel panel, String title, String tooltip) {
        int index = tabbedPane.indexOfComponent(panel);
        if (index == -1) {
            logger.error("Cannot find the requested component in the tabs, so I cannot change its title");
            return;
        }
        tabbedPane.setTitleAt(index, title); // <--  CAUSES THE ERROR
        tabbedPane.setToolTipTextAt(index, tooltip);
    }
```

Alas, I cannot build a mcve of this. 

So I've narrowed down the issue. This is the Exception trace:
~~~
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTextViewForTab(BasicTabbedPaneUI.java:1706)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.calculateTabHeight(BasicTabbedPaneUI.java:1717)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI.calculateTabHeight(FlatTabbedPaneUI.java:686)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.calculateMaxTabHeight(BasicTabbedPaneUI.java:1742)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI.calculateMaxTabHeight(FlatTabbedPaneUI.java:698)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateTabRects(BasicTabbedPaneUI.java:2586)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateLayoutInfo(BasicTabbedPaneUI.java:2512)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.layoutContainer(BasicTabbedPaneUI.java:2407)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$FlatTabbedPaneLayout.layoutContainer(FlatTabbedPaneUI.java:2443)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validate(Container.java:1628)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:704)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:702)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:701)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1719)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

And this is the lowest point I could follow the code:
![image](https://user-images.githubusercontent.com/50494/111475598-8afc4a00-872d-11eb-8d62-77d184334abd.png)

**Comment by DevCharly** [comment]
Could you please post the stack trace of the exception?

**Comment by lgvr123** [comment]
Added to topic. I submitted it too fast.

**Comment by DevCharly** [comment]
Very strange. Was not yet able to reproduce it...

What Java version do you use?
Does it work with other LaFs?

**Comment by lgvr123** [comment]
> Does it work with other LaFs?
I should have verified. Same issue with Metal L&F. 
It appears when switched to FlatLaf and abandoned the JideSof TabbedPane for the Java native one.
So it is not related to FlatFlat.

**Comment by DevCharly** [comment]
Class `BasicTabbedPaneUI` maintains field `Vector<View> htmlViews`, which seems to be not updated correctly.
Is it possible that parsing of the HTML string causes an exception?

I would set an breakpoint at following line:
https://github.com/openjdk/jdk/blob/e152cc0312915d48efc67a133195b38ee9e45306/src/java.desktop/share/classes/javax/swing/plaf/basic/BasicTabbedPaneUI.java#L4035

If it does not stop there, then there could be an exception in the previous line.

Another possibility: Do you invoke `setTileFor()` while processing a `PropertyChangeEvent` on the tabbedpane? Then it could be possible that field `BasicTabbedPaneUI.htmlViews` is not yet up-to-date.

**Comment by lgvr123** [comment]
Thanks for the suggestions. I'll investigate it. It is not blocking.

**Comment by DevCharly** [comment]
Any news on this?

**Comment by lgvr123** [comment]
I had not time to test. And I'm in the process of removing JideSoft because it breaks the execution on Linux. I'll retest after to see if it was correlated.
I'd close this issue here because it is not related to FlatLaf.
