### ISSUE TITLE
Problems with JideButton with WindowsLaF with FlatLaf 1.1

### ISSUE THREAD

**Issue by schliepRon** [JFormDesigner/FlatLaf#288]
When using the flatlaf 1.1 libs  I get the following Exception with the Windows Look&Feel.

With a Flatlaf Look&Feel it works fine and with flatlaf 1.0 it also works with the Windows Look&Feel.

Dont know if I messed smth up with a custom UIManager key or a general problem with flatlaf 1.1.

java.lang.NullPointerException
	at sun.font.FontDesignMetrics$MetricsKey.init(FontDesignMetrics.java:217)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:286)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
	at com.jidesoft.plaf.basic.BasicJideButtonUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at com.jidesoft.pane.OutlookTabbedPane$h_.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at java.awt.Container.validateUnconditionally(Container.java:1670)
	at java.awt.Window.show(Window.java:1033)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)

**Comment by DevCharly** [comment]
Seems that font of button is `null`. Have no idea and can not reproduce.

Could you debug it?

I wonder how FlatLaf is involved.
Do you first setup FlatLaf and then switch to Windows Laf?

**Comment by schliepRon** [comment]
Not sure why, but seems to be necessary to set the UIManager keys of JideButton.font etc when I use flatlaf 1.1. 
At least I fixed it that way.

Answering your question from above:

I initialize only the Look&Feel chosen by the user . So either Windows or FlatLaf.
After that I call LookAndFeelFactory.installJideExtension();

Now I additionally set the missing UIManager keys for the Jide Components.

**Comment by DevCharly** [comment]
Still trying to understand/reproduce what happens in your case...

There is some new code in FlatLaf 1.1 that modifies fonts:
https://github.com/JFormDesigner/FlatLaf/blob/277c28895296cc3576f22ed3e866f80def63a47e/flatlaf-jide-oss/src/main/java/com/formdev/flatlaf/jideoss/FlatJideOssDefaultsAddon.java#L111-L121

But this code is actually only invoked if FlatLaf is used.
And the `defaults` hash table used by this code is not used by Windows L&F (which has its own instance).

Anyway could you please set a breakpoint at the above code and check whether it is invoked when you use Windows L&F ?
If it stops, please post the stack trace.
Thanks.

BTW what JIDE version do you use?

**Comment by DevCharly** [comment]
Please also disable your fix and set a breakpoint at following line:
https://github.com/JFormDesigner/FlatLaf/blob/277c28895296cc3576f22ed3e866f80def63a47e/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java#L851

If this is invoked from Windows L&F, then `font` is probably `null`, which could explain the NPE...

**Comment by schliepRon** [comment]
Both Breakpoints hit.


```
"de.mdsi.spencer.startup.Main.main()@2742" prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.formdev.flatlaf.jideoss.FlatJideOssDefaultsAddon$FlatJideUIDefaultsCustomizer.customize(FlatJideOssDefaultsAddon.java:111)
	  at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source:-1)
	  at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source:-1)
	  at de.mdsi.spencer.session.Utilities.reloadLaF(Utilities.java:1604)
	  at de.mdsi.spencer.startup.SessionStartUp.startSession(SessionStartUp.java:106)
	  at de.mdsi.spencer.startup.Main.main(Main.java:202)
	  at java.lang.invoke.LambdaForm$DMH.1144870862.invokeStaticInit_L_V(LambdaForm$DMH:-1)
	  at java.lang.invoke.LambdaForm$MH.17348384.invoke_MT(LambdaForm$MH:-1)
	  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	  at java.lang.Thread.run(Thread.java:748)

```
`"de.mdsi.spencer.startup.Main.main()@2742" prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.formdev.flatlaf.FlatLaf$ActiveFont.createValue(FlatLaf.java:771)
	  at javax.swing.UIDefaults.getFromHashtable(UIDefaults.java:231)
	  at javax.swing.UIDefaults.get(UIDefaults.java:161)
	  at javax.swing.MultiUIDefaults.get(MultiUIDefaults.java:64)
	  at javax.swing.UIDefaults.getFont(UIDefaults.java:388)
	  at javax.swing.UIManager.getFont(UIManager.java:672)
	  at javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:208)
	  at com.jidesoft.plaf.basic.BasicJideButtonUI.installDefaults(Unknown Source:-1)
	  at com.jidesoft.plaf.basic.BasicJideButtonUI.installUI(Unknown Source:-1)
	  at javax.swing.JComponent.setUI(JComponent.java:666)
	  at com.jidesoft.swing.JideButton.updateUI(Unknown Source:-1)
	  at javax.swing.AbstractButton.init(AbstractButton.java:2176)
	  at javax.swing.JButton.<init>(JButton.java:137)
	  at javax.swing.JButton.<init>(JButton.java:91)
	  at com.jidesoft.swing.JideButton.<init>(Unknown Source:-1)
	  at com.jidesoft.swing.JideButton.<init>(Unknown Source:-1)
	  at com.jidesoft.pane.OutlookTabbedPane.<init>(Unknown Source:-1)
	  at de.mdsi.spencer.component.SpencerMenuPanel.initComponents(SpencerMenuPanel.java:137)
	  at de.mdsi.spencer.component.SpencerMenuPanel.<init>(SpencerMenuPanel.java:58)
	  at de.mdsi.spencer.component.OutlookFrame.initComponents(OutlookFrame.java:393)
	  at de.mdsi.spencer.component.OutlookFrame.<init>(OutlookFrame.java:132)
	  at de.mdsi.spencer.startup.SessionStartUp.startSession(SessionStartUp.java:137)
	  at de.mdsi.spencer.startup.Main.main(Main.java:202)
	  at java.lang.invoke.LambdaForm$DMH.1284892188.invokeStaticInit_L_V(LambdaForm$DMH:-1)
	  at java.lang.invoke.LambdaForm$MH.703568603.invoke_MT(LambdaForm$MH:-1)
	  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	  at java.lang.Thread.run(Thread.java:748)
`

**Comment by DevCharly** [comment]
Thx.

The first stack looks strange to me. In my case it is much deeper:
~~~
Thread [AWT-EventQueue-0] (Suspended (breakpoint at line 111 in FlatJideOssDefaultsAddon$FlatJideUIDefaultsCustomizer))	
	FlatJideOssDefaultsAddon$FlatJideUIDefaultsCustomizer.customize(UIDefaults) line: 111	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	LookAndFeelFactory.invokeCustomize(UIDefaults, String) line: 1309	
	LookAndFeelFactory.customize(String, UIDefaults) line: 1292	
	LookAndFeelFactory.installJideExtension(UIDefaults, LookAndFeel, int) line: 1075	
	LookAndFeelFactory.installJideExtension(int) line: 637	
	LookAndFeelFactory.installJideExtension() line: 602	
...
~~~

In your stack `FlatJideUIDefaultsCustomizer.customize()` is invoked directly from `LookAndFeelFactory.installJideExtension()`.

This can only happen if you use something like:
~~~java
LookAndFeelFactory.addUIDefaultsCustomizer(new FlatJideUIDefaultsCustomizer());
~~~

Do you?

This would explain everything because then `FlatJideUIDefaultsCustomizer.customize()` is also invoked for Windows L&F (or any other laf) and replaces the font with an `ActiveFont`. Because Windows L&F does not have a `defaultFont` UI value, following line in `ActiveFont.createValue()` returns `null` and the `JideButton` font becomes `null`.
https://github.com/JFormDesigner/FlatLaf/blob/277c28895296cc3576f22ed3e866f80def63a47e/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java#L834

Try without using `LookAndFeelFactory.addUIDefaultsCustomizer()`.
FlatLaf should work without this.

I will add some checks to `FlatJideUIDefaultsCustomizer` so that code is executed only if FlatLaf is active.

**Comment by schliepRon** [comment]
Yes I do.

tyvm
