### ISSUE TITLE
JFileChooser issue

### ISSUE THREAD

**Issue by AlexAzarXYZ** [JFormDesigner/FlatLaf#304]
Hey there, I am using flat laf 1.1 with the dark orange theme. When creating a JFile chooser and showing it this error comes: 

_**Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.formdev.flatlaf.ui.FlatTitlePane.findHorizontalGlue(FlatTitlePane.java:463)
	at com.formdev.flatlaf.ui.FlatTitlePane.updateNativeTitleBarHeightAndHitTestSpots(FlatTitlePane.java:715)
	at com.formdev.flatlaf.ui.FlatTitlePane.lambda$updateNativeTitleBarHeightAndHitTestSpotsLater$5(FlatTitlePane.java:675)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)**_
......

Here is the code I used: 

JFrame parentFrame = new JFrame();

JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Specify where to save the file and its Name");
fileChooser.setCurrentDirectory(new File(
System.getProperty("user.home") + System.getProperty("file.separator") + "Desktop"));
int userSelection = fileChooser.showSaveDialog(parentFrame);

Any idea what it could be ?

**Comment by DevCharly** [comment]
Looks like #275.

Please try FlatLaf 1.1.2

**Comment by AlexAzarXYZ** [comment]
All fixed ! Thanks for this fast response !! :D
