### ISSUE TITLE
NPE in FlatPopupFactory.fixToolTipLocation

### ISSUE THREAD

**Issue by rogerbj** [JFormDesigner/FlatLaf#305]
Since we introduced FlatLaf the following exception has been reported by multiple users. We have unfortunately not been able to reproduce nor have any test case.

Using FlatLaf 1.0. Any idea?

```
java.lang.NullPointerException
   at com.formdev.flatlaf.ui.FlatPopupFactory.fixToolTipLocation(FlatPopupFactory.java:219)
   at com.formdev.flatlaf.ui.FlatPopupFactory.getPopup(FlatPopupFactory.java:65)
   at java.desktop/javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:350)
   at java.desktop/javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:693)
   at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
   at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
   at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
   at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
   at java.base/java.security.AccessController.doPrivileged(Native Method)
   at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
   at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
   at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
   at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
   at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DevCharly** [comment]
Seems that `MouseInfo.getPointerInfo()` returns `null` here:
https://github.com/JFormDesigner/FlatLaf/blob/5eab843d976acf9ba052eff6d453a87f57640722/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPopupFactory.java#L219

This is probably related to multi-monitor setups.

On single-monitor setups, `MouseInfo.getPointerInfo()` never returns `null`.

On multi-monitor setups, `MouseInfo.getPointerInfo()` iterates over the connected screens to find the device where the mouse pointer currently is located. If not found, it returns `null`. But I don't know how this could happen. At least on Windows 10 I can not move the mouse outside of any screen. Maybe it is different on other platforms...

Anyway, will add a `null` check to fix this issue...

**Comment by DevCharly** [comment]
Should be fixed in main branch.

Let me know in case you need a FlatLaf 1.0.1 release with this fix.
