### ISSUE TITLE
UnsupportedClassVersionError on Java 8 on Windows 10 when compiling with JDK11/16

### ISSUE THREAD

**Issue by srett** [JFormDesigner/FlatLaf#370]
We've added FlatLaf to an old Java app, which looks much better now.  :-)
Compiling on Linux using OpenJDK 11 or 16, setting the targeted Java Version to 8 via the maven-compiler-plugin's `<release>` option. The resulting jar works fine on Linux with OpenJRE 8, 11 and 16.

However on a Windows 10 install with Oracle Java 8, we get
`java.lang.UnsupportedClassVersionError: com/formdev/flatlaf/util/MultiResolutionImageSupport has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Installing OpenJDK 8 on Linux to compile the app yields a jar that is working on Windows. Is this a known limitation?

The Windows machine runs
```
java.version                  1.8.0_301
java.vm.version               25.301-b09
java.runtime.version          1.8.0_301-b09
```

Full stack trace:
```
java.lang.UnsupportedClassVersionError: com/formdev/flatlaf/util/MultiResolutionImageSupport has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.formdev.flatlaf.FlatLaf.getDisabledIcon(FlatLaf.java:215)
	at javax.swing.AbstractButton.getDisabledIcon(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonUI.paintIcon(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonUI.paint(Unknown Source)
	at com.formdev.flatlaf.ui.FlatButtonUI.paint(FlatButtonUI.java:367)
	at com.formdev.flatlaf.ui.FlatButtonUI.update(FlatButtonUI.java:309)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by DevCharly** [comment]
To avoid such problems I strongly recommend to use the pre-compiled FlatLaf binaries from maven central.

If correctly built, `flatlaf-<version>.jar` is a multi-release JAR.
The classes in JAR folder `com/formdev/flatlaf` are compiled for Java 8,
but the classes in JAR folder `META-INF/versions/9/com/formdev/flatlaf` are compiled for Java 9.

`MultiResolutionImageSupport` is one of those classes.

Compiling FlatLaf with Java 8 is not recommended because then the resulting JAR does not contain `META-INF/versions/9` and some functionality is lost.

**Comment by srett** [comment]
That's exactly what we're doing, I think. This is what we added to our pom.xml:

```
   <dependency>
           <groupId>com.formdev</groupId>
           <artifactId>flatlaf</artifactId>
           <version>1.5</version>
           <scope>compile</scope>
   </dependency>
```

Then we call `FlatLightLaf.installLafInfo(); UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");` in our main method. The app mostly runs, but has graphical errors and throws exceptions similar to the above in certain spots. Unfortunately this occurs with a remote user, we don't have a Windows machine here, but to speed things up I'll try to borrow one.

**Comment by srett** [comment]
Found the culprit:
For the `maven-assembly-plugin`, there was a `<version>3.0.0</version>` tag set, which eclipse even annotated with a yellow squiggly line. After removing it, I get different class files in the final .jar, as maven is now reportedly using version `2.2-beta-5` of that plugin. Now if I only knew whether the version was set for a specific reason... But that's a different problem on our end. :-)
I'll send the Windows user a new jar and close the issue if this solves the problem. Thanks for hinting at the multi-release thing!

**Comment by srett** [comment]
> Ok, so repackage the FlatLaf jar into your application jar, right?

Yes. We're building a "fat jar" so it's easy to distribute to end users which are sometimes in restricted environments. This is achieved through this:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-assembly-plugin</artifactId>
	<version>3.0.0</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>single</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<archive>
			<manifest>
				<mainClass>${main.class}</mainClass>
				<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
				<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
			</manifest>
		</archive>
		<descriptorRefs>
			<descriptorRef>jar-with-dependencies</descriptorRef>
		</descriptorRefs>
	</configuration>
</plugin>
```

For some reason, having the version 3.0.0 tag there resulted in all the classes from the `META-INF/versions/9/` path of FlatLaf being copied to the root of the final jar, replacing the Java 8 versions of those classes. Removing the version tag allows maven to use the default version of the plugin (however that is determined), which didn't do this. Now it's still interesting that the broken jar still worked on Linux when using jre-8, it seems the according classes weren't needed there.

`Multi-Release: true` doesn't end up in the final jar yet though, but this is easy to fix. I assume not having this results in Java 9+ also using the old classes with missing features...

Anyways, everything is fine and dandy now on Windows, mystery solved. :-)
