### ISSUE TITLE
Layout loop caused by FlatSplitPaneUI

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#513]
Hello,

I'm hitting a layout loop that is triggered by FlatSplitPaneDivider#propertyChange which calls revalidate().

There was a JSplitPane that has an invisible component at the bottom, and it was added into a JideSplitPane (the continuous layout was enabled). The issue happened when dragging the JideSplitPaneDivider to resize the JideSplitPane then somehow called the inner JSplitPane's setDividerLocation(), and the stacktrace came out:

~~~
java.lang.StackOverflowError
	at java.base/sun.util.logging.PlatformLogger.isLoggable(PlatformLogger.java:340)
	at java.desktop/java.awt.Container.mixOnReshaping(Container.java:4322)
	at java.desktop/java.awt.Component.reshape(Component.java:2364)
	at java.desktop/javax.swing.JComponent.reshape(JComponent.java:4241)
	at java.desktop/java.awt.Component.setBounds(Component.java:2326)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.setComponentToSize(BasicSplitPaneUI.java:1774)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.layoutContainer(BasicSplitPaneUI.java:1415)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Component.revalidateSynchronously(Component.java:3090)
	at java.desktop/java.awt.Component.revalidate(Component.java:3065)
	at com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider.propertyChange(FlatSplitPaneUI.java:238)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:287)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8771)
	at java.desktop/javax.swing.JComponent.firePropertyChange(JComponent.java:4545)
	at java.desktop/javax.swing.JSplitPane.setDividerLocation(JSplitPane.java:798)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.layoutContainer(BasicSplitPaneUI.java:1443)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Component.revalidateSynchronously(Component.java:3090)
	at java.desktop/java.awt.Component.revalidate(Component.java:3065)
	at com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider.propertyChange(FlatSplitPaneUI.java:238)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:287)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8771)
	at java.desktop/javax.swing.JComponent.firePropertyChange(JComponent.java:4545)
	at java.desktop/javax.swing.JSplitPane.setDividerLocation(JSplitPane.java:798)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.layoutContainer(BasicSplitPaneUI.java:1443)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Component.revalidateSynchronously(Component.java:3090)
	at java.desktop/java.awt.Component.revalidate(Component.java:3065)
~~~
Is it an issue that can be fixed in a similar way as #420?

Cheers,
Tristan

**Comment by DevCharly** [comment]
Thanks for reporting.

Should be fixed in main branch.
Please try the latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
Does it work now?

**Comment by tristanzhou** [comment]
It works. Thanks.
