### ISSUE TITLE
LaF doesn't remove listeners

### ISSUE THREAD

**Issue by rjahn** [JFormDesigner/FlatLaf#537]
I have an application which supports a restart. The application opens a JFrame and on restart, the JFrame will be disposed and another JFrame will be created...

The special feature is that every application has it's own ClassLoader and the "old" ClassLoader will be closed.

So, in my case, the new frame throws an Exception because the old-frame receives an event and tries to load a class, but the classloader is already closed....

The exception:

```
java.lang.NoClassDefFoundError: com/formdev/flatlaf/ui/FlatUIUtils$NonUIResourceBorder
    at com.formdev.flatlaf.ui.FlatUIUtils.nonUIResource(FlatUIUtils.java:193)
    at com.formdev.flatlaf.ui.FlatTitlePane.updateIcon(FlatTitlePane.java:363)
    at com.formdev.flatlaf.ui.FlatTitlePane$Handler.propertyChange(FlatTitlePane.java:951)
    at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
    at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
    at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
    at java.desktop/java.awt.Component.firePropertyChange(Component.java:8728)
    at java.desktop/java.awt.Window.setIconImages(Window.java:717)
    at java.desktop/java.awt.Window.setIconImage(Window.java:752)
    at java.desktop/java.awt.Frame.setIconImage(Frame.java:558)
    at java.desktop/javax.swing.JFrame.setIconImage(JFrame.java:645)
```

The problem was solved after removing property change listeners from UIManager manually.

**Comment by DevCharly** [comment]
> The special feature is that every application has it's own ClassLoader and the "old" ClassLoader will be closed.

Does this mean that the Java VM is **not** restarted?
And FlatLaf "runs" in your own ClassLoader?

> The problem was solved after removing property change listeners from UIManager manually.

Which listener did you remove?

**Comment by rjahn** [comment]
same VM, only new frame, yes - new class loader.

```
	        PropertyChangeListener[] lis = UIManager.getPropertyChangeListeners();
	        
	        if (lis != null)
	        {
		        for (int i = 0; i < lis.length; i++)
		        {
		        	UIManager.removePropertyChangeListener(lis[i]);
		        }
	        }

```

**Comment by rjahn** [comment]
Not sure, but in my debug code, I did more:

```
try
{
    LookAndFeel laf = UIManager.getLookAndFeel();

    if (laf != null)
    {
    	laf.uninitialize();
    }
}
catch (Throwable th)
{
	//ignore
}

UIManager.getDefaults().clear();
PropertyChangeListener[] lis = UIManager.getPropertyChangeListeners();

if (lis != null)
{
    for (int i = 0; i < lis.length; i++)
    {
    	UIManager.removePropertyChangeListener(lis[i]);
    }
}

Frame[] frame = JFrame.getFrames();

if (frame != null)
{
    for (int i = 0; i < frame.length; i++)
    {
    	frame[i].dispose();
    }
}

Window[] win = Window.getWindows();

if (win != null)
{
    for (int i = 0; i < win.length; i++)
    {
    	win[i].dispose();
    }
}
```

but the exception was about property change listeners....

**Comment by DevCharly** [comment]
Could you please add following, before removing listeners, and post the output here:
~~~java
for( PropertyChangeListener l : UIManager.getPropertyChangeListeners() ) {
    System.out.println( l );
}
~~~

**Comment by rjahn** [comment]
com.formdev.flatlaf.util.UIScale$1@4169fe90

**Comment by DevCharly** [comment]
The `UIScale` listener added to `UIManager` updates only the scale factor when the font is changed.
There is no relation to Swing components or to the active Laf.

I have no idea why this listener should cause the exception in the first post...

> The special feature is that every application has it's own ClassLoader and the "old" ClassLoader will be closed.

Is Swing also loaded by this ClassLoader?
Or only application libraries?

**Comment by rjahn** [comment]
You're right. The listener isn't the problem.

Swing is loaded by the application classloader, not my classloader. The problem is that my classloader is already closed and this triggers the exception, because the "old" classloader is not able to load any classes.

The problem doesn't occur right now because of 

```
Frame[] frame = JFrame.getFrames();

if (frame != null)
{
    for (int i = 0; i < frame.length; i++)
    {
    	frame[i].dispose();
    }
}
```

But it's not clear why setIconImage on new frame tries to change the icon of the old frame as well. Do you have a frame cache in your code?

**Comment by DevCharly** [comment]
> Do you have a frame cache in your code?

Hmm, don't think so...

The three `Flat*` methods in the exception stack are invoked only from the frame where `JFrame.setIconImage()` was invoked. So setting a icon on a new frame should now change anything on other frames.

Looking at the following line (see also exception), it seems that `FlatUIUtils.nonUIResource()` is only invoked if icon is not `null`. E.g. for `frame.setIconImage( null )`. 

https://github.com/JFormDesigner/FlatLaf/blob/6c18431a305cd14712f8704d261365ff5f775091/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L363

So the exception should not occur if you assign an icon to a frame.
Are you sure that the frame that causes the exception is a new one?

**Comment by rjahn** [comment]
I'm sure because the setIconImage method is called during init of my new application for the new frame. 

Very strange. I'm setting null as initial value... but this shouldn't create a new FlatEmptyBorder.... you're right.

My use-case is not usual and disposing the frame is recommended, so this problem can be avoided.

**Comment by DevCharly** [comment]
BTW it is strange that classes `FlatTitlePane` and `FlatUIUtils` could be loaded, but `FlatUIUtils$NonUIResourceBorder` not...
If `FlatUIUtils` was loaded in new classloader, why does it try to load `FlatUIUtils$NonUIResourceBorder` in old classloader.

> My use-case is not usual and disposing the frame is recommended, so this problem can be avoided.

Yes, newer seen this before 🤔

**Comment by rjahn** [comment]
An unusual use-case... It's related to custom classloading. So it's not a general FlatLaF problem. In my case, closing classloader and disposing frame solved the problem. If other users have the same problem... maybe they have better test-cases.
