### ISSUE TITLE
JMenuBar NullPointer

### ISSUE THREAD

**Issue by rjahn** [JFormDesigner/FlatLaf#538]
My application runs under MacOS and system property: 

`System.setProperty("apple.laf.useScreenMenuBar", "true");`

enables Mac system menu bar...

In every swing application, it's possible to create a new instance of JMenuBar and add the bar e.g. in the North of a Border layout. If you do this, an exception is the result:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.desktop/com.apple.laf.AquaMenuPainter.paintMenuBarBackground(AquaMenuPainter.java:149)
	at java.desktop/com.apple.laf.AquaMenuBarUI.paint(AquaMenuBarUI.java:82)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DevCharly** [comment]
The exception in [AquaMenuPainter.paintMenuBarBackground](https://github.com/openjdk/jdk/blob/6a7709320d28d8e1593b113fdf39ab583fca3687/src/java.desktop/macosx/classes/com/apple/laf/AquaMenuPainter.java#L149) occurs because UI property [MenuBar.backgroundPainter](https://github.com/openjdk/jdk/blob/6a7709320d28d8e1593b113fdf39ab583fca3687/src/java.desktop/macosx/classes/com/apple/laf/AquaMenuPainter.java#L142) is `null` in your case.

But FlatLaf sets UI property `MenuBar.backgroundPainter` here:

https://github.com/JFormDesigner/FlatLaf/blob/5f961618bf8f86c4bf16f6c21ae8aac1e275a9ba/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java#L463-L464

See issues #90 and #287

Here is a test case that demonstrates that it works:

~~~java
import java.awt.BorderLayout;
import javax.swing.*;
import com.formdev.flatlaf.FlatDarkLaf;

public class TestAquaMenuBar
{
	public static void main( String[] args ) {
		System.setProperty( "apple.laf.useScreenMenuBar", "true" );

		SwingUtilities.invokeLater( () -> {
			FlatDarkLaf.setup();

//			try {
//				UIManager.setLookAndFeel( new javax.swing.plaf.metal.MetalLookAndFeel() );
//			} catch( UnsupportedLookAndFeelException ex ) {
//				ex.printStackTrace();
//			}

			JFrame frame = new JFrame( "TestAquaMenuBar" );
			frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );

			JMenu fileMenu = new JMenu( "File" );
			fileMenu.add( new JMenuItem( "Open" ) );

			JMenuBar menuBar = new JMenuBar();
			menuBar.add( fileMenu );
			frame.getContentPane().add( menuBar, BorderLayout.NORTH );

			frame.setBounds( 100, 100, 300, 200 );
			frame.setVisible( true );
		});
	}
}
~~~

However, if you're using Metal or Nimbus and Java 9+, then the NPE is thrown.
See this comment: https://github.com/JFormDesigner/FlatLaf/issues/287#issuecomment-808213288

Maybe this has something to do with your classloaders that you mentioned in #537 ?

**Comment by rjahn** [comment]
The problem is not related to my class loader because it's the first application start. The problem can be avoided if I set 

  System.setProperty("apple.laf.useScreenMenuBar", "false");

before creating the JMenuBar.

I'll create a simple demo application.

**Comment by rjahn** [comment]
ok, clear. The problem is that the 

  System.setProperty("apple.laf.useScreenMenuBar", "false");

call is after LaF was set. In my application, the macOS detection is later... and it's a modular system. This is the reason why it wasn't set before application initialization.

You recognize the system property in LaF creation, so this is the cause.

**Comment by DevCharly** [comment]
You need to set `apple.laf.useScreenMenuBar` before initializing FlatLaf.

Either set it always (it does not harm on other OSes),
or use `com.formdev.flatlaf.util.SystemInfo.isMacOS`.
