### ISSUE TITLE
Jframe to set property "type" to "UTILITY" Failed 

### ISSUE THREAD

**Issue by jiangguilong2000** [JFormDesigner/FlatLaf#568]
7月 16, 2022 9:33:57 下午 Component: this
严重: Failed to set property "type" to "UTILITY".
java.awt.IllegalComponentStateException: The window is displayable.
	at java.desktop/java.awt.Window.setType(Window.java:2924)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.jformdesigner.tD.a(SourceFile:613)
	at com.jformdesigner.yK.a(SourceFile:1259)
	at com.jformdesigner.yK.d(SourceFile:910)
	at com.jformdesigner.yK.a(SourceFile:825)
	at com.jformdesigner.no.a(SourceFile:113)
	at com.jformdesigner.yK.a(SourceFile:810)
	at com.jformdesigner.Sq.a(SourceFile:1488)
	at com.jformdesigner.Xp.b(SourceFile:251)
	at com.jformdesigner.Xp.d(SourceFile:339)
	at com.jformdesigner.Xp.a(SourceFile:334)
	at com.jformdesigner.XB.b(SourceFile:310)
	at com.jformdesigner.XB.b(SourceFile:21)
	at com.jformdesigner.bY.run(SourceFile:450)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

when i set the value from normal to utility ,the error is throwed.
![image](https://user-images.githubusercontent.com/5009933/179357356-1aace159-d941-413d-b9cd-ccc6c5a893e3.png)
![image](https://user-images.githubusercontent.com/5009933/179357501-39d2871e-217c-4306-b10c-00c0d9497f9e.png)

the enviroment is as follows:
JDK: TencentKona8.0.8 based as openjdk 8 
and oracle JDK jdk1.8.0_66  is also crash down.
windows 11

and other question is that why the title bar is white ? how to set the bar's color same as other component
![image](https://user-images.githubusercontent.com/5009933/179357472-74e162ea-4fcc-4710-89ee-7d778198fbcd.png)

**Comment by DevCharly** [comment]
Please report [JFormDesigner (Java/Swing GUI Designer)](https://www.formdev.com/jformdesigner/) related issues to support@formdev.com.

You can simply ignore the exception. It does not affect the functionality of JFormDesigner.

We'll fix both issues in the next version.
Thanks for reporting.

**Comment by jiangguilong2000** [comment]
> Both issues are fixed in JFormDesigner 7.0.7: https://www.formdev.com/jformdesigner/download/

GOOD JOB!!!
