### ISSUE TITLE
FlatStylingSupport$UnknownStyleException: unknown style 'toolbar.margin'

### ISSUE THREAD

**Issue by legendmohe** [JFormDesigner/FlatLaf#597]
```
// search history button
    val historyBtn = JButton(FlatSearchWithHistoryIcon(true))
    historyBtn.toolTipText = "Search History"
    historyBtn.border = BorderFactory.createEmptyBorder(0, 6, 0, 4)
    historyBtn.background = ThemeConstant.COLOR_TRANSPARENT
    historyBtn.addActionListener {
        if (srcInputList.size <= 0) {
            return@addActionListener
        }
        val popup = createHistoryPopup(
            popupMenuFactory = popupMenuFactory,
            srcInputList = srcInputList,
            curText = textField.text,
            onItemSelected = {
                textField.text = it.content
                onItemSelected?.invoke(it)
            }
        )
        popup.show(historyBtn, 0, historyBtn.height)
    }
    textField.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_COMPONENT, historyBtn) <---- UnknownStyleException
```

I got a UnknownStyleException exception when I put an JButton to a JTextField as a leading component:

```
com.formdev.flatlaf.ui.FlatStylingSupport$UnknownStyleException: unknown style 'toolbar.margin'
	at com.formdev.flatlaf.ui.FlatStylingSupport.applyToField(FlatStylingSupport.java:472)
	at com.formdev.flatlaf.ui.FlatStylingSupport.applyToAnnotatedObject(FlatStylingSupport.java:412)
	at com.formdev.flatlaf.ui.FlatStylingSupport.applyToAnnotatedObjectOrBorder(FlatStylingSupport.java:652)
	at com.formdev.flatlaf.ui.FlatButtonUI.applyStyleProperty(FlatButtonUI.java:364)
	at com.formdev.flatlaf.ui.FlatButtonUI.lambda$applyStyle$2(FlatButtonUI.java:344)
	at com.formdev.flatlaf.ui.FlatStylingSupport.applyStyle(FlatStylingSupport.java:336)
	at com.formdev.flatlaf.ui.FlatStylingSupport.parseAndApply(FlatStylingSupport.java:301)
	at com.formdev.flatlaf.ui.FlatButtonUI.applyStyle(FlatButtonUI.java:343)
	at com.formdev.flatlaf.ui.FlatButtonUI.installStyle(FlatButtonUI.java:330)
	at com.formdev.flatlaf.ui.FlatButtonUI.installUIImpl(FlatButtonUI.java:205)
	at com.formdev.flatlaf.ui.FlatButtonUI.installUI(FlatButtonUI.java:199)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.AbstractButton.setUI(AbstractButton.java:1753)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at com.formdev.flatlaf.ui.FlatButtonUI.propertyChange(FlatButtonUI.java:318)
	at com.formdev.flatlaf.ui.FlatButtonUI$FlatButtonListener.propertyChange(FlatButtonUI.java:798)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8732)
	at java.desktop/javax.swing.JComponent.putClientProperty(JComponent.java:4117)
	at com.formdev.flatlaf.ui.FlatTextFieldUI.prepareLeadingOrTrailingComponent(FlatTextFieldUI.java:842)
	at com.formdev.flatlaf.ui.FlatTextFieldUI.installLeadingComponent(FlatTextFieldUI.java:725)
	at com.formdev.flatlaf.ui.FlatTextFieldUI.propertyChange(FlatTextFieldUI.java:270)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1913)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8732)
	at java.desktop/javax.swing.JComponent.putClientProperty(JComponent.java:4117)
```

**Comment by DevCharly** [comment]
Do not change the border (and the background) of the button.
This is not necessary.
FlatLaf does it for you 😉 
There is a style defined in properties files:

https://github.com/JFormDesigner/FlatLaf/blob/6e7c2a616ba72f4829f9db86fd77c096858f9db6/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties#L374-L382

Because `toolbar.margin` is a style in the buttons default border (class `FlatButtonBorder`),
you should not replace the button border.
