### ISSUE TITLE
FlatSVGIcon Issue - Could not parse

### ISSUE THREAD

**Issue by Kokecena** [JFormDesigner/FlatLaf#661]
I am trying to use the svg icons from this page https://tabler-icons.io but it sends me the following error  and it does not show at least the red icon

The error says that the specified file is not found, I already tried a clean, or a clean and build in my maven project, but I don't need to do that when I use another icon that I download from 'X' page

```java
abr. 05, 2023 12:11:32 P. M. com.kitfox.svg.SVGUniverse loadSVG
ADVERTENCIA: Could not parse
java.io.FileNotFoundException: C:\Users\jovan\Desktop\ReproductorDeMusicaBASS\target\classes\icons\currentColor (El sistema no puede encontrar el archivo especificado)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:495)
	at com.kitfox.svg.SVGUniverse.getElement(SVGUniverse.java:375)
	at com.kitfox.svg.SVGUniverse.getElement(SVGUniverse.java:309)
	at com.kitfox.svg.ShapeElement.renderShape(ShapeElement.java:206)
	at com.kitfox.svg.Path.doRender(Path.java:94)
	at com.kitfox.svg.BufferPainter.paintElement(BufferPainter.java:57)
	at com.kitfox.svg.RenderableElement.render(RenderableElement.java:116)
	at com.kitfox.svg.Group.doRender(Group.java:205)
	at com.kitfox.svg.SVGRoot.doRender(SVGRoot.java:306)
	at com.kitfox.svg.BufferPainter.paintElement(BufferPainter.java:57)
	at com.kitfox.svg.RenderableElement.render(RenderableElement.java:116)
	at com.kitfox.svg.SVGRoot.renderToViewport(SVGRoot.java:250)
	at com.kitfox.svg.SVGDiagram.render(SVGDiagram.java:114)
	at com.kitfox.svg.SVGDiagram.render(SVGDiagram.java:125)
	at com.formdev.flatlaf.extras.FlatSVGIcon.paintSvg(FlatSVGIcon.java:621)
	at com.formdev.flatlaf.extras.FlatSVGIcon.paintIcon(FlatSVGIcon.java:593)
	at com.formdev.flatlaf.ui.FlatMenuItemRenderer.paintIcon(FlatMenuItemRenderer.java:463)
	at com.formdev.flatlaf.ui.FlatMenuItemRenderer.paintIcon(FlatMenuItemRenderer.java:425)
	at com.formdev.flatlaf.ui.FlatMenuItemRenderer.paintMenuItem(FlatMenuItemRenderer.java:355)
	at com.formdev.flatlaf.ui.FlatMenuUI.paint(FlatMenuUI.java:226)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.update(BasicMenuItemUI.java:617)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

``` 

It is the only site where this error occurs, look for another icon on another page that will fit the one I want and it works without problems https://www.svgrepo.com

**Comment by DevCharly** [comment]
The problem is that the tabler icons use `stroke="currentColor"`, which seems to be not supported by SVG Salamander (the SVG rendering library used by FlatSVGIcon).

Please report the issue here: https://github.com/blackears/svgSalamander

To workaround the problem, edit the SVG file and replace `stroke="currentColor"` with `stroke="#000"` (or other color).

**Comment by weisJ** [comment]
Just stumbled upon this issue and wanted to chime in that with the new sag imlementation the `currentColor` keyword is now supported.
