### ISSUE TITLE
Dynamic Font Loading causes Security Issues

### ISSUE THREAD

**Issue by genebarker** [JFormDesigner/FlatLaf#668]
Please consider including the required extra fonts in the jars.

I recently tried to upgrade from FlatLaf 2.5 for our Java WebStart app. The app experienced weird security issues after deployment. After tracing the log, found that it would not permit the dynamic loading of fonts (a new introduction after 2.5). The visual result was a weird 'double spacing' effect ruining the beautiful look of the applicable themes (GitHub, Light Owl, Material Oceanic, etc.) - Like that in Issue #667.

We'll be migrating away shortly from Java 1.8 and WebStart, so am not sure this will continue to be an issue.

Even so, for security purposes, I'm not comfortable with enterprise app libraries dynamically loading things. And FlatLaf is kinda awesome for enterprise apps :-)

**Comment by DevCharly** [comment]
Thanks for reporting, but I'm a little bit confused...

> Please consider including the required extra fonts in the jars

What are the "required extra fonts"?

There are jars that include fonts (see https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-fonts)

> The app experienced weird security issues after deployment.

What does this mean? 😕 

> After tracing the log, found that it would not permit the dynamic loading of fonts 

Could you please give some more information? Stack trace, log, etc.

Currently, I have no idea what is going wrong and how to fix it...

**Comment by genebarker** [comment]
OK, give me a moment. With our POM, we must manually specify every jar. Maybe I missed it. Will follow-up. Our users really love their themes!

**Comment by genebarker** [comment]
Saw your comment on #667 - this is the effect I'm seeing. A security exception throws when the app is deployed. This is new behavior and caught my eye. Here's the new exception we don't see with 3.1 (but not 2.5).

'''
2023-04-17 12:17:13.744 [javawsApplicationMain] INFO  com.madman.sifa.client.StandardClient - Perform app startup seqeunce.
2023-04-17 12:17:13.745 [javawsApplicationMain] DEBUG com.madman.sifa.client.StandardClient - App started with following arguments: [].
2023-04-17 12:17:13.746 [javawsApplicationMain] INFO  com.madman.sifa.client.StandardClient - JNLP services loaded.
2023-04-17 12:17:13.747 [javawsApplicationMain] INFO  com.madman.sifa.client.StandardClient - Server hostname (t2.mysifa.ws) retrieved from JNLP services.
2023-04-17 12:17:13.753 [javawsApplicationMain] INFO  com.madman.sifa.client.StandardClient - App preferences (/com/madman/sifa/client) loaded.
JNLPClassLoader: Finding library jawt.dll
Apr 17, 2023 12:17:13 PM com.formdev.flatlaf.util.LoggingFacadeImpl logSevere
SEVERE: URI scheme is not "file"
java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(Unknown Source)
	at com.formdev.flatlaf.ui.FlatNativeLibrary.findLibraryBesideJar(FlatNativeLibrary.java:135)
	at com.formdev.flatlaf.ui.FlatNativeLibrary.createNativeLibrary(FlatNativeLibrary.java:107)
	at com.formdev.flatlaf.ui.FlatNativeLibrary.initialize(FlatNativeLibrary.java:81)
	at com.formdev.flatlaf.ui.FlatNativeLibrary.isLoaded(FlatNativeLibrary.java:42)
	at com.formdev.flatlaf.ui.FlatNativeWindowsLibrary.isLoaded(FlatNativeWindowsLibrary.java:35)
	at com.formdev.flatlaf.util.SystemInfo.<clinit>(SystemInfo.java:131)
	at com.formdev.flatlaf.FlatLaf.initialize(FlatLaf.java:258)
	at javax.swing.UIManager.setLookAndFeel(Unknown Source)
	at com.madman.sifa.client.StandardClient.setLookAndFeel(StandardClient.java:541)
	at com.madman.sifa.client.StandardClient.setLookAndFeel(StandardClient.java:531)
	at com.madman.sifa.client.StandardClient.lambda$main$0(StandardClient.java:486)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

2023-04-17 12:17:14.200 [AWT-EventQueue-2] INFO  com.madman.sifa.client.StandardClient - App look and feel set to Material Oceanic.
'''

**Comment by DevCharly** [comment]
Thanks, looks like you see two independent issues.

A fix for #667 will be available soon.

The exception, which actually has nothing to do with security or with font loading, occurs when trying to locate the FlatLaf DLL outside of the FlatLaf jar (issue #624). Seems that there is something different when the application runs in WebStart...

Anyway, you can ignore this exception. It is caught and FlatLaf continues to work. Probably it extracts the DLL from the JAR to a temporary directory and loads it from there (which is the default behavior).

**Comment by DevCharly** [comment]
fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by genebarker** [comment]
Thank you and great work. Can't wait for 3.2 official!

**Comment by DevCharly** [comment]
FlatLaf 3.1.1 is now available

**Comment by genebarker** [comment]
Deployed. Works great. Thank you! Beautiful :-)
