### ISSUE TITLE
NullPointerException in ProgessBar

### ISSUE THREAD

**Issue by ClarkCodes** [JFormDesigner/FlatLaf#677]
### Context Information
Hi, greetings, I would like to report a bug.
* Versions used:
FlatLaf: 3.1.1
Java: OpenJDK 17.0.2 - 64-Bit Server VM 17.0.2+8-86
Gradle: 8.1
OS: Windows 10 - ver 10.0.19045.2846
IDE: Apache NetBeans IDE 17

### Important Note
I must mention that I was using a previous FlatLaf version( FlatLaf 2.1 ) and it was woking fine, it was working great, this happened just after perform an upgrade to the latest version 3.1.1 in my dependencies specification in my build.gradle file. I was trying versions out to find one where it doesn't happen to set my app [Cinema Tickets](https://github.com/ClarkCodes/CinemaTickets) to that version, and I found that this error only happens with the versions 3.1.1 and 3.1, it doesn't happen with the 3.0, so I set my app with this last one.

### How the bug occurs?
In my case, I have a `ProgressBar` on indeterminate state in my Splash jFrame window, so just by running my app without doing anything at all( it happens every time I run it ) and just when my app opens occurs a `NullPointerException` with the following description and stack trace:

### StackTrace
>\> Task :run
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "width" because "this.componentInnards" is null
	at java.desktop/javax.swing.plaf.basic.BasicProgressBarUI.updateSizes(BasicProgressBarUI.java:542)
	at java.desktop/javax.swing.plaf.basic.BasicProgressBarUI.getBox(BasicProgressBarUI.java:499)
	at com.formdev.flatlaf.ui.FlatProgressBarUI.paint(FlatProgressBarUI.java:230)
	at com.formdev.flatlaf.ui.FlatProgressBarUI.update(FlatProgressBarUI.java:201)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1340)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
May 03, 2023 5:40:47 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet

### Thank you :)
I hope this could help in some way or just bring visibility to a blind corner and this way, eventually, fix it properly. 
I love your work, thank you very much in advance for your time, patience and help.

**Comment by ClarkCodes** [comment]
# Update about it
I was making some general changes in my app code, doing some tests and trying things, and I found out that performing a 'clean and build' operation on the project when using the version 3.1, the exception  dissapears and then it works just fine, but it persists when using the 3.1.1 version, it doesn't matter if I perform 3 or 5 clean and build operations, it keeps happening, so apparently it is related with some step or something that is not being completely taken into account in this latest release.

**Comment by DevCharly** [comment]
This is not a bug in FlatLaf.
It is a threading issue in your app.

You're invoking `UIManager.setLookAndFeel()` and `FlatLaf.updateUI()` on a worker thread (which is not allowed),
while at the same time Swing repaints the indeterminate progress bar on AWT thread.

Swing is not thread safe.
Invoke Swing methods that modify look&feel or components only on AWT thread.
Use `EventQueue.invokeLater()`.

Maybe FlatLaf 3.1 initialization is a little bit slower than in previous versions, which cause the issue.
If you add `Thread.sleep( 10 );` to your app, after calling `FlatLaf.updateUI()`, you get the same exception with FlatLaf 2.1.

**Comment by ClarkCodes** [comment]
Okaay, interesting... then I should check the thread management in my app on that part, I didn't know that, sorry... thank you very much @DevCharly for the help. 👍🏼 :D
