### ISSUE TITLE
Security Exception with System.getProperty() when using OpenWebStart & Scripting

### ISSUE THREAD

**Issue by rcuprak** [JFormDesigner/FlatLaf#689]
The Flat Look & Feel makes use of System.getProperty() in some parts of the code base during initialization. The use of System.getProperty() is problematic when an application is being run via OpenWebStart as it may not have permission to make this call resulting in an AccessControlException. In the application I am working on, UI validations can be customized via Java's scripting support (use provides a custom script). Most of the customizations are done via JavaScript and thus the System.getProperty() is a problem. I don't see this problem with other L&Fs. 

I have created a demo application replicating this issue:
https://github.com/rcuprak/flatlaf-defect-demo

To replicate, you need OpenWebStart installed (https://openwebstart.com). The JNLP file in the repo goes against signed JARs in the release. Interestingly, I cannot reproduce it on ARM based Macs - only Windows. 

The exception seen on Windows:
... 59 more
    at com.formdev.flatlaf.ui.FlatNativeWindowBorder.<clinit>(FlatNativeWindowBorder.java:55)
    at com.formdev.flatlaf.FlatSystemProperties.getBoolean(FlatSystemProperties.java:182)
    at java.base/java.lang.System.getProperty(System.java:816)
    at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
    at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:272)
    at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
    at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
    at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "flatlaf.useWindowDecorations" "read")
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
    at java.desktop/java.awt.Container.processEvent(Container.java:2263)
    at java.desktop/java.awt.Component.processEvent(Component.java:6400)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
    at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
    at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    at net.cuprak.flatlaf.TestProgram.actionPerformed(TestProgram.java:113)
    at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
    at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
    at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
    at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
    at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
    at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
    at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
    at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1$\^eval\_/0x0000000100567040.:program(<eval>:1)
    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:612)
    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
    at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:871)
    at java.desktop/javax.swing.JOptionPane.createDialog(JOptionPane.java:963)
    at java.desktop/javax.swing.JDialog.<init>(JDialog.java:280)
    at java.desktop/javax.swing.JDialog.dialogInit(JDialog.java:649)
    at java.desktop/javax.swing.JDialog.createRootPane(JDialog.java:670)
    at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:353)
    at java.desktop/javax.swing.JRootPane.updateUI(JRootPane.java:459)
    at java.desktop/javax.swing.JRootPane.setUI(JRootPane.java:449)
    at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
    at com.formdev.flatlaf.ui.FlatRootPaneUI.installUI(FlatRootPaneUI.java:108)
    at com.formdev.flatlaf.ui.FlatRootPaneUI.installNativeWindowBorder(FlatRootPaneUI.java:234)
java.lang.ExceptionInInitializerError
Denying permission: ("java.util.PropertyPermission" "flatlaf.useWindowDecorations" "read")

**Comment by DevCharly** [comment]
> The use of System.getProperty() is problematic when an application is being run via OpenWebStart as it may not have permission to make this call resulting in an AccessControlException.

Is this somewhere documented?
I've not found any information about this restriction.
Maybe it is a bug in OpenWebStart ?

>  Interestingly, I cannot reproduce it on ARM based Macs - only Windows.

So on Windows usage or System.getProperty() is restricted, but not on macOS.
Definitely sounds like a bug in OpenWebStart...

> Most of the customizations are done via JavaScript and thus the System.getProperty() is a problem.

Not sure whether the restriction has something to do with JavaScript...

Your `TestProgram` creates the initial UI using Metal L&F, then setups FlatLaf,
then the next dialog is created using FlatLaf via JavaScript.

If you change the `main()` method of `TestProgram` to following, the exception is probably thrown at startup, right? (I've not yet tried):

~~~java
SwingUtilities.invokeLater( () -> {
    FlatLightLaf.setup();
    final TestProgram tp = new TestProgram();
    tp.init();
} );
~~~

BTW can't you simply give your application access to `flatlaf.*` system properties?

**Comment by rcuprak** [comment]
In the JNLP file I have <security><all-permissions></security>. It was my understanding that to grant access to flatlaf.* would require a local policy file change in the JRE?

**Comment by DevCharly** [comment]
This is a bug in OpenWebStart: https://github.com/karakun/OpenWebStart/issues/76
