### ISSUE TITLE
Invalid Location

### ISSUE THREAD

**Issue by mumbel** [JFormDesigner/FlatLaf#698]
```
Invalid location
java.lang.IllegalArgumentException: Invalid location
	at java.desktop/javax.swing.text.JTextComponent.getSelectedText(JTextComponent.java:1784)
	at java.desktop/javax.swing.text.DefaultCaret.updateSystemSelection(DefaultCaret.java:1390)
	at java.desktop/javax.swing.text.DefaultCaret.focusGained(DefaultCaret.java:385)
	at com.formdev.flatlaf.ui.FlatCaret.focusGained(FlatCaret.java:150)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:228)
	at java.desktop/java.awt.Component.processFocusEvent(Component.java:6515)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1061)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:687)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Came across this clicking a window (I think, not 100% what triggered it) in Ghidra 10.3.1 (https://github.com/NationalSecurityAgency/ghidra/issues/5539), which ships with FlatLaf 2.6, and using ubuntu 22.04 and JDK 17.0.7.  Not sure if there's enough info to go off of, but figured worth reporting here too in case.

**Comment by DevCharly** [comment]
The exception is triggered when focusing a text component.
Can you remember what text component you clicked on or which was focused?
Is this reproducible?

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
