### ISSUE TITLE
Null Pointer Exception on Windows shortcut panel

### ISSUE THREAD

**Issue by ptorngren** [JFormDesigner/FlatLaf#718]
One of our users reported an error which seems to be caused by the `FlatShortcutsPanel` constructor not accounting for a `null` name, which `javax.swing.filechooser.FileSystemView.getSystemDisplayName()` may return.

We get the following stack trace in FlatLaf 3.0:
~~~
java.lang.NullPointerException: Cannot invoke "String.lastIndexOf(int)" because "name" is null
   at com.formdev.flatlaf.ui.FlatFileChooserUI$FlatShortcutsPanel.<init>(FlatFileChooserUI.java:444)
   at com.formdev.flatlaf.ui.FlatFileChooserUI.createShortcutsPanel(FlatFileChooserUI.java:318)
   at com.formdev.flatlaf.ui.FlatFileChooserUI.installComponents(FlatFileChooserUI.java:181)
   at java.desktop/javax.swing.plaf.basic.BasicFileChooserUI.installUI(BasicFileChooserUI.java:209)
   at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.installUI(MetalFileChooserUI.java:159)
   at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
   at java.desktop/javax.swing.JFileChooser.updateUI(JFileChooser.java:1839)
   at com.onseven.dbvis.util.gui.r.b.updateUI(Z:320)
   at java.desktop/javax.swing.JFileChooser.setup(JFileChooser.java:396)
   at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:362)
   at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:349)
~~~

**Comment by DevCharly** [comment]
Was not able to reproduce the NPE...

Anyway, improved the implementation and ignore items where file or name are null.

If you need a quick fix for FlatLaf 3.0, you could use following:

~~~java
public class MyFlatFileChooserUI extends FlatFileChooserUI {
    public static ComponentUI createUI( JComponent c ) {
        return new MyFlatFileChooserUI( (JFileChooser) c );
    }

    public MyFlatFileChooserUI( JFileChooser filechooser ) {
        super( filechooser );
    }

    @Override
    protected FlatShortcutsPanel createShortcutsPanel( JFileChooser fc ) {
        return new MyFlatShortcutsPanel( fc );
    }

    public static class MyFlatShortcutsPanel extends FlatShortcutsPanel {
        public MyFlatShortcutsPanel( JFileChooser fc ) {
            super( fc );
        }

        @Override
        protected String getDisplayName( FileSystemView fsv, File file ) {
            String name = super.getDisplayName( fsv, file );
            return name != null ? name : "???";
        }
    }
}
~~~

To enable above class use:

~~~java
if( UIManager.getLookAndFeel() instanceof FlatLaf )
    UIManager.put( "FileChooserUI", MyFlatFileChooserUI.class.getName() );
else
    UIManager.put( "FileChooserUI", null );
~~~
