### ISSUE TITLE
Flatlaf 3.2.1 generates InaccessibleObjectException where Flatlaf 2.1 did not.

### ISSUE THREAD

**Issue by i-make-robots** [JFormDesigner/FlatLaf#741]
Java 15
IntelliJ 2023.2.2
Main project https://www.github.com/marginallyclever/makelangelo-software/

Updated from flatlaf 2.1 to 3.2.1.  The app still runs.  Every attempt to create a dialog creates stderr output similar to:
```
Oct. 02, 2023 10:43:42 A.M. com.formdev.flatlaf.util.LoggingFacadeImpl logSevere
SEVERE: null
java.lang.reflect.InaccessibleObjectException: Unable to make public java.awt.Image sun.awt.shell.Win32ShellFolder2.getIcon(boolean) accessible: module java.desktop does not "opens sun.awt.shell" to module com.formdev.flatlaf
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:301)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
	at com.formdev.flatlaf/com.formdev.flatlaf.ui.FlatFileChooserUI$FlatShortcutsPanel.getIcon(FlatFileChooserUI.java:552)
	at com.formdev.flatlaf/com.formdev.flatlaf.ui.FlatFileChooserUI$FlatShortcutsPanel.<init>(FlatFileChooserUI.java:444)
	at com.formdev.flatlaf/com.formdev.flatlaf.ui.FlatFileChooserUI.createShortcutsPanel(FlatFileChooserUI.java:320)
	at com.formdev.flatlaf/com.formdev.flatlaf.ui.FlatFileChooserUI.installComponents(FlatFileChooserUI.java:183)
	at java.desktop/javax.swing.plaf.basic.BasicFileChooserUI.installUI(BasicFileChooserUI.java:209)
	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.installUI(MetalFileChooserUI.java:159)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JFileChooser.updateUI(JFileChooser.java:1838)
	at java.desktop/javax.swing.JFileChooser.setup(JFileChooser.java:395)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:361)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:308)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.SaveDialog.<clinit>(SaveDialog.java:17)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.MainMenu.<init>(MainMenu.java:42)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.Makelangelo.<init>(Makelangelo.java:70)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.Makelangelo.lambda$main$6(Makelangelo.java:435)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DevCharly** [comment]
Yes, it is not optimal that this is logged every time a file chooser is opened... 
You can ignore it.

Anyway, I would recommend using Java 17 or 21, which do not have this problem.
Java 15 should not be used anymore.

**Comment by i-make-robots** [comment]
Oh heck, are we up to 21 already?  I can't keep up.... lol.  Changing to 21 made the report go away.
Thank you for the fast reply!
