### ISSUE TITLE
Exception during SwingUtilities.updateComponentTreeUI when updating to light or dark FaltLaf

### ISSUE THREAD

**Issue by Surcouf01** [JFormDesigner/FlatLaf#742]
Hello,

I am in the process of adding dark or light theme (FlatDarkLaf or FlatLightLaf LookAndFeel), and in the process of switching from dark to light or light to dark I get an exception in the SwingUtilities.updateComponentTreeUI( w ), see below.
I'm not sure it's a FlatLaf problem, but it does not if the application is run with others LookAndFeels.
Here is the exception :
~~~
java.lang.IllegalArgumentException: cannot add to layout: unknown constraint: divider
        at java.desktop/java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:468)
        at java.desktop/java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:429)
        at java.desktop/java.awt.Container.addImpl(Container.java:1156)
        at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1015)
        at java.desktop/java.awt.Container.add(Container.java:1001)
        at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI.installDefaults(BasicSplitPaneUI.java:362)
        at com.formdev.flatlaf.ui.FlatSplitPaneUI.installDefaults(FlatSplitPaneUI.java:113)
        at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI.installUI(BasicSplitPaneUI.java:325)
        at com.formdev.flatlaf.ui.FlatSplitPaneUI.installUI(FlatSplitPaneUI.java:98)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
        at java.desktop/javax.swing.JSplitPane.setUI(JSplitPane.java:373)
        at java.desktop/javax.swing.JSplitPane.updateUI(JSplitPane.java:400)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
        at arinc661.appli.ARINC661App.updateUI(ARINC661App.java:1948)
        at arinc661.appli.ARINC661App.setDarkTheme(ARINC661App.java:1941)
        at arinc661.appli.ARINCSettings.lambda$initializeEditorSettings$33(ARINCSettings.java:1115)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:411)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.repostEvent(BasicTableUI.java:987)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1203)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.awt.BorderLayout.addLayoutComponent(468) cannot add to layout: unknown constraint: divider
~~~

**Comment by Surcouf01** [comment]
Here is the concerned piece of code:
```
   public void setDarkTheme(boolean darkTheme) {
      try {
         if (darkTheme) {
            UIManager.setLookAndFeel(new FlatDarkLaf());
         } else {
            UIManager.setLookAndFeel(new FlatLightLaf());
         }
         SwingUtilities.invokeLater(() -> updateUI());
      } catch (Exception e) {
         Logging.err(e);
      }
   }
   public static void updateUI() {
      for( Window w : Window.getWindows() ) {
         SwingUtilities.updateComponentTreeUI(w);
      }
   }
```
The method setDarkTheme is called on the onActionListener of a JCheckBox inside a settings panel.
