### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "croppedEdge" because "this.this$0.tabScroller" is null

### ISSUE THREAD

**Issue by Surcouf01** [JFormDesigner/FlatLaf#744]
Hello,

I am in the process to add support to light and dark themes to our application.
Currently the option to dark theme is controlled by a `JCheckBox` that results in a delayed action that calls the UIManager.setLookAndFeel method.
Code is as follow:
```
   public void setDarkTheme(boolean darkTheme) {
      try {
         if (darkTheme) {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
         } else {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
         }
         updateUI();
      } catch (Exception e) {
         Logging.err(e);
      }
   }
   public static void updateUI() {
      for( Window w : Window.getWindows() ) {
         SwingUtilities.updateComponentTreeUI(w);
      }
   }
```
and
```
      cbDarkTheme = new JCheckBox("", appliConf.isDarkTheme());
      cbDarkTheme.addActionListener(e -> {
         if (setAppliConfig) {
            appliConf.setDarkTheme(cbDarkTheme.isSelected());
         }
         this.appli.executeThemeAction(cbDarkTheme.isSelected());
      });
```
The problem is that a NullPointerException is fired when the components are being revalidated:
```
java.lang.NullPointerException: Cannot read field "croppedEdge" because "this.this$0.tabScroller" is null
        at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneScrollLayout.layoutContainer(BasicTabbedPaneUI.java:3375)
        at java.desktop/java.awt.Container.layout(Container.java:1541)
        at java.desktop/java.awt.Container.doLayout(Container.java:1530)
        at java.desktop/java.awt.Container.validateTree(Container.java:1725)
        at java.desktop/java.awt.Container.validateTree(Container.java:1734)
        at java.desktop/java.awt.Container.validateTree(Container.java:1734)
        at java.desktop/java.awt.Container.validate(Container.java:1660)
        at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:757)
        at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:755)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:754)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I'm using JDK 17, code at BasicTabbedPaneUI.java:3375 is:
```
            if (tabPane.getTabCount() == 0) {
                tabScroller.croppedEdge.resetParams();
                tabScroller.scrollForwardButton.setVisible(false);
                tabScroller.scrollBackwardButton.setVisible(false);
                return;
            }
```
Code is accessing tabScroller looking at tabPane.getTabCount(), whereas everywhere else in this class the code looks at scrollableTabLayoutEnabled()

Plus the UI updates partially, this should not be related to NPE because it's executed in a separate thread.
![image](https://github.com/JFormDesigner/FlatLaf/assets/146843183/f6d436e6-932f-41ab-b5f3-fc80cf9571e0)

Could that be a JDK issue, before filling a bug report I was prefering referring to you as I use the FlatLaf library.

**Comment by DevCharly** [comment]
> Plus the UI updates partially, this should not be related to NPE because it's executed in a separate thread.

You're changing L&F and updating UI in another thread?
Then this is the reason for the problem.
Swing is not thread safe.

Setting L&F and updating UI is only allowed on AWT thread.
