### ISSUE TITLE
No ComponentUI class for Swing component when using FlatLaf 

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#771]
We have a gradle project in which we included the flatlaf-3.2.5.jar for look and feel of the application. When we try to launch the application from the command line, application splash screen is stuck on the screen with the following error in the logs.

`java.lang.Error: no ComponentUI class for: javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)`

If we do launch application from intellij, everything works fine. Can you please help to resolve this issue. 

Application info:
We have a mainframe and we calling the `FlatLaf.setup(new FlatLightLaf());
		FlatLightLaf.setup();`
to set the L&F to flatlaf.

**Comment by DevCharly** [comment]
Could be a threading issue.
On which thread did the exception occur?

**Comment by VKaddala** [comment]
I am executing this on EDT. I found the fix for the issue and is fixed when flatlaf.jar is injected into jvm explicitly by using -XBootClassPath. Now we stuck with another problem. We made a custom properties file to register the properties for L&F. We are making this file along with some custom borders and packed into a jar. When the application is launched, it is applying the properties from the file, instead coming out as flatlightlaf theme.

**Comment by DevCharly** [comment]
> We have a mainframe and we calling the `FlatLaf.setup(new FlatLightLaf()); FlatLightLaf.setup();`
to set the L&F to flatlaf.

Only one is needed. Either `FlatLaf.setup(new FlatLightLaf())` **or** `FlatLightLaf.setup()`.

> I am executing this on EDT.

Do you invoke `FlatLightLaf.setup()` also on EDT?
And before any Swing component is created?

> ... flatlaf.jar is injected into jvm explicitly by using -XBootClassPath.

This is not necessary to use FlatLaf.
There is something else wrong in your application.

**Comment by VKaddala** [comment]
Actually, we need to do setup after Mainframe (which is basically JavaFX and swing combo) is created. Everything works fine except the changes from properties file as I mentioned in above comment. Can you please help me to figure what may went wrong.

**Comment by DevCharly** [comment]
> ...except the changes from properties file...

Well, if FlatLaf is on bootclasspath, then it tries to find classes/resources also on bootclasspath, but this does not include application classes/resources. You probably need to pass the application classloader to FlatLaf register method.
E.g.

```java
FlatLaf.registerCustomDefaultsSource( "com.mypackage", this.getClass().getClassLoader() );
```
