### ISSUE TITLE
NPE on Windows 11 when the application is left idle for sometime and actions are performed again

### ISSUE THREAD

**Issue by aditya-dk7** [JFormDesigner/FlatLaf#782]
I am trying to integrate the FlatLAF light theme with my application, and when the application is left idle for some time, and interacted with again throws an exception with the following stack trace:

```
java.lang.NullPointerException
	at com.formdev.flatlaf.FlatClientProperties.clientPropertyBoolean(FlatClientProperties.java:1208)
	at com.formdev.flatlaf.ui.FlatTreeUI.isWideSelection(FlatTreeUI.java:794)
	at com.formdev.flatlaf.ui.FlatTreeUI$1.handleWideMouseEvent(FlatTreeUI.java:278)
	at com.formdev.flatlaf.ui.FlatTreeUI$1.mousePressed(FlatTreeUI.java:264)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Any idea why this might be happening?? I am using the properties file for setting up the desired UI for all the components. For the tree specifically I am using the following:

```
Tree.selectionBackground=#CDE6EB
Tree.selectionForeground=#000000
Tree.expandedIcon=com.lookandfeel.FlatTreeExpandedIcon
Tree.collapsedIcon=com.lookandfeel.FlatTreeMinimizedIcon
Tree.paintLines=true
Tree.lineTypeDashed=true
Tree.selectionInactiveBackground=#CDE6EB
Tree.hash=#707070
Tree.textForeground=#464646
Tree.font=14 "Segoe UI"
Tree.wideSelection=true
```
Is this related to the Tree.wideSelection property?? Please advise

**Comment by DevCharly** [comment]
This is very strange.

The NPE shows that field `BasicTreeUI.tree` is null, which is only the case after uninstalling the UI (switching to another theme/L&F).
It seems that the FlatLaf tree mouse listener is not removed for some reason...

Because I can not reproduce the problem, I think that there is something in your code that causes the problem.

Did you switch to another theme/L&F before the problem occurs?
Or do you invoke `FlatLaf.updateUI()` or `SwingUtilities.updateComponentTreeUI()` or `component.updateUI()`?
Do you manipulate the mouse listeners on that tree? E.g. get all mouse listeners, do something, and then restore mouse listeners?

I would suggest to set a breakpoint at following line:

https://github.com/JFormDesigner/FlatLaf/blob/38b26410784a4372bbc5c7af4f290a7a8da5a10e/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java#L264

Check whether variable `this.this$0.tree` is not null and equal to variable `e.source`:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/206a7ab0-a5df-4262-987a-952187e10d65)

Also check whether variable `this.this$0` (a FlatTreeUI) is equal to variable `e.source.ui`:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/dfb8e88e-1128-46a4-87a4-2fd82fc4abe4)

**Comment by aditya-dk7** [comment]
Thanks for such a prompt response. The issue is very strange indeed, and I have been unable to pinpoint what might be the reason for such an exception.

As you requested, I have checked the following things after adding the breakpoint at the `super.mousePressed( handleWideMouseEvent( e ) );` :

1. The variable `this.this$0.tree` is not null and  is equal to variable `e.source`
2. Moreover, `this.this$0` (a FlatTreeUI) is also equal to variable `e.source.ui`
3. We are not switching to another UI at all. We do the `FlatLightLaf.setup();` in the beginning & that's it

I could not find any discrepancies there. Moreover, the `FlatLaf.updateUI()` or `SwingUtilities.updateComponentTreeUI()` or `component.updateUI()` are not getting called from the code.

Finally, the mouse listeners are getting added once, but are not removed or manipulated.

Another thing is to note that while setting the UI of the tree, we doing the following (to incorporate some logic here):
```
m_tree.setUI(new FlatTreeUI()
{

	protected boolean isToggleEvent(MouseEvent evt)
	{
	   // Custom logic here to stop toggle on double click
        }
});

```
This exception was also **not reproduced consistently**, I could only do it twice from which I got the stack trace

If you need some other information, please feel free to ask I can provide

**Comment by aditya-dk7** [comment]
Hi, I tried to do some more digging and I am now able to reproduce the issue consistently. Following is the sample code:

```
import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class SwingTree {
    public static void main(String[] args) {
        FlatLightLaf.setup();
        JFrame frame = new JFrame("JTree MouseListener Example");
        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Root");
        DefaultMutableTreeNode node1 = new DefaultMutableTreeNode("Node 1");
        DefaultMutableTreeNode node2 = new DefaultMutableTreeNode("Node 2");
        rootNode.add(node1);
        rootNode.add(node2);

        JTree tree = new JTree(rootNode);
        JScrollPane scrollPane = new JScrollPane(tree);

        tree.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                tree.updateUI();
            }
        });

        frame.add(scrollPane);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 200);
        frame.setVisible(true);
    }
}
```

You were right about calling the update UI method, it is getting called as above in our code. Now, I tried replacing the `tree.updateUI()` using `SwingUtilities.invokeLater(()->{tree.updateUI();});` which evaded the NPE. Following are my questions regarding this:
1. As the swing UI is supposed to be run on the EDT thread, is this problem occurring as we are not calling updateUI in invokeLater? Because the mouseReleased event is on EDT thread right?? This is what is making me confused. If I queue an invoke later, the runnable will be run at some later point, and is that the reason I cannot see the problem getting reproduced or is there some more specific logic involved?


I am new to manipulating swing UI components, and it would be of great help if you could explain me the problem.

**Comment by aditya-dk7** [comment]
@DevCharly Did you get a chance to look at the same?

**Comment by aditya-dk7** [comment]
Could anyone please help?

**Comment by DevCharly** [comment]
> You were right about calling the update UI method, it is getting called as above in our code.

And why is `updateUI()` called in your code?
What do you expect from this method?
Are you sure what this method is good for?

If you don't know what this method does or what it is good for, then **do not use it**!

`updateUI()` is usually invoked from Swing for component constructors and when switching L&F/theme using `SwingUtilities.updateComponentTreeUI()`.

There is **no need to call this method from user/application code**.

Regarding the NPE, which is caused by this code:

~~~java
tree.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseReleased(MouseEvent e) {
        tree.updateUI();
    }
});
~~~

Calling `tree.updateUI();` uninstalls the old `FlatTreeUI` instance, which sets field `BasicTreeUI.tree` to `null`,
but the mouse listener of that old `FlatTreeUI` instance is still processed and throws that NPE because `BasicTreeUI.tree` is `null` in that old `FlatTreeUI` instance.

So if you know what you're doing and really need to invoke `tree.updateUI()`,
then use `SwingUtilities.invokeLater()` in that case.
