### ISSUE TITLE
No ComponentUI class for Swing component when using FlatLaf - When CustomUI class is provided.

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#789]
Actually, we need to do setup after Mainframe (which is basically JavaFX and swing combo) is created. Everything works fine except the changes from properties file as I mentioned in above comment. Can you please help me to figure what may went wrong.

We have optionPaneUI has follow - OptionPaneUI =utilities.ui.FlatCustomOptionPaneUI

Flatlaf is on bootclasspath... and i used FlatLaf.registerCustomDefaultsSource( "utilities.ui", this.getClass().getClassLoader() ); to register the property file. But stll i am getting following error. 

~~~
javax.swing.JOptionPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,icon=,initialValue=Exit Application,message=[Ljava.lang.Object;@747216b6,messageType=ERROR_MESSAGE,optionType=DEFAULT_OPTION,wantsInput=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1873)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1838)
~~~

**Comment by DevCharly** [comment]
Could be a similar cloassloader problem as in #777...

What is the error message?
It is missing in your post.
Error message should start with `UIDefaults.getUI() failed:`

**Comment by VKaddala** [comment]
Now the same error is coming from different place.
`java.lang.Error: no ComponentUI class for: com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider$FlatOneTouchButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
	at java.desktop/javax.swing.plaf.basic.BasicArrowButton.<init>(BasicArrowButton.java:82)
	at com.formdev.flatlaf.ui.FlatArrowButton.<init>(FlatArrowButton.java:63)
	at com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider$FlatOneTouchButton.<init>(FlatSplitPaneUI.java:297)
	at com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider.createLeftOneTouchButton(FlatSplitPaneUI.java:232)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneDivider.oneTouchExpandableChanged(BasicSplitPaneDivider.java:378)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneDivider.propertyChange(BasicSplitPaneDivider.java:338)
	at com.formdev.flatlaf.ui.FlatSplitPaneUI$FlatSplitPaneDivider.propertyChange(FlatSplitPaneUI.java:242)
`

can you please look into this. @DevCharly

**Comment by VKaddala** [comment]
`public class CustomFlatLaf extends FlatLightLaf
{

	public CustomFlatLaf()
	{
	}

	public static boolean setup()
	{
		return setup(new CustomFlatLaf());
	}

	public static void installLafInfo()
	{
		installLafInfo("Custom FlatLaf Light", CustomFlatLaf.class);
	}

	@Override public boolean getSupportsWindowDecorations()
	{
		if (SystemInfo.isLinux) {
			return true;
		}
		return super.getSupportsWindowDecorations();
	}
}`

we have created this custom flat laf class for getting linux and this is the only initilization part we did. @DevCharly

**Comment by DevCharly** [comment]
> can you please look into this. @DevCharly

LOL. Sure, I'm a clairvoyant and can solve your classloader issues without any information 😉

**Comment by DevCharly** [comment]
> Flatlaf is on bootclasspath... and i used FlatLaf.registerCustomDefaultsSource( "utilities.ui", this.getClass().getClassLoader() ); to register the property file

You could try to specify a classloader for Swing:

~~~java
UIManager.put( "ClassLoader", this.getClass().getClassLoader() );
~~~
