### ISSUE TITLE
java.lang.Error: createUI() failed for com.formdev.flatlaf.ui.FlatScrollBarUI$FlatScrollBarButton

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#818]
When we try to create a dialog, we encounter the following error multiple times.
Please look into the stack trace provided below.

~~~
java.lang.Error: createUI() failed for com.formdev.flatlaf.ui.FlatScrollBarUI$FlatScrollBarButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true] java.lang.reflect.InvocationTargetException
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:811)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
	at java.desktop/javax.swing.plaf.basic.BasicArrowButton.<init>(BasicArrowButton.java:82)
	at com.formdev.flatlaf.ui.FlatArrowButton.<init>(FlatArrowButton.java:63)
	at com.formdev.flatlaf.ui.FlatScrollBarUI$FlatScrollBarButton.<init>(FlatScrollBarUI.java:512)
	at com.formdev.flatlaf.ui.FlatScrollBarUI$FlatScrollBarButton.<init>(FlatScrollBarUI.java:505)
	at com.formdev.flatlaf.ui.FlatScrollBarUI.createIncreaseButton(FlatScrollBarUI.java:328)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installComponents(BasicScrollBarUI.java:288)
	at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.installUI(BasicScrollBarUI.java:208)
	at com.formdev.flatlaf.ui.FlatScrollBarUI.installUI(FlatScrollBarUI.java:131)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JScrollBar.setUI(JScrollBar.java:210)
	at java.desktop/javax.swing.JScrollBar.updateUI(JScrollBar.java:231)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:182)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:702)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(JScrollPane.java:854)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:300)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.createScroller(BasicComboPopup.java:614)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.<init>(BasicComboPopup.java:371)
	at com.formdev.flatlaf.ui.FlatComboBoxUI$FlatComboPopup.<init>(FlatComboBoxUI.java:841)
	at com.formdev.flatlaf.ui.FlatComboBoxUI.createPopup(FlatComboBoxUI.java:414)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.installUI(BasicComboBoxUI.java:289)
	at com.formdev.flatlaf.ui.FlatComboBoxUI.installUIImpl(FlatComboBoxUI.java:184)
	at com.formdev.flatlaf.ui.FlatComboBoxUI.installUI(FlatComboBoxUI.java:180)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
~~~

**Comment by DevCharly** [comment]
Can not reproduce...

Maybe it has something to do with using FlatLaf on bootclasspath (your previous issues #771 and #789).

I would suggest to set a breakpoint at following line:
https://github.com/openjdk/jdk/blob/6ae1cf12cee268ac7599eb9ade9c0861a89748f9/src/java.desktop/share/classes/javax/swing/UIDefaults.java#L818
and check the value of "Exception e" to find out where the `InvocationTargetException` came from.

Or use Java 12 or later. Then Swing outputs that exception stack...
