### ISSUE TITLE
Popup: possible npe from java.awt.Component#getGraphicsConfiguration

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#921]
Hello. I'm testing Consulo(IDEA fork) with FlatLaf and getting this error. I'm not sure for now - on which side, but depends on javadoc - this method can return null

```
Cannot invoke "java.awt.GraphicsConfiguration.isTranslucencyCapable()" because the return value of "java.awt.Component.getGraphicsConfiguration()" is null: Cannot invoke "java.awt.GraphicsConfiguration.isTranslucencyCapable()" because the return value of "java.awt.Component.getGraphicsConfiguration()" is null
java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.isTranslucencyCapable()" because the return value of "java.awt.Component.getGraphicsConfiguration()" is null
	at consulo.desktop.awt/com.formdev.flatlaf/com.formdev.flatlaf.ui.FlatPopupFactory.getPopup(FlatPopupFactory.java:141)
	at consulo/consulo.ide.impl@3-SNAPSHOT/consulo.ide.impl.idea.ui.popup.PopupComponent$Factory$AwtHeavyweight.getPopup(PopupComponent.java:69)
	at consulo/consulo.ide.impl@3-SNAPSHOT/consulo.ide.impl.idea.ui.popup.AbstractPopup.show(AbstractPopup.java:973)
	at consulo/consulo.ide.impl@3-SNAPSHOT/consulo.ide.impl.idea.ui.popup.AbstractPopup.show(AbstractPopup.java:494)
	at consulo/consulo.ide.impl@3-SNAPSHOT/consulo.ide.impl.idea.ide.HelpTooltipImpl.lambda$scheduleShow$4(HelpTooltipImpl.java:468)
```

**Comment by DevCharly** [comment]
Thanks for reporting.

Fixed in latest `3.5.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
