### ISSUE TITLE
Linux: NPE when using FlatLaf window decorations and switching theme (regression in 3.5.3)

### ISSUE THREAD

**Issue by DevCharly** [JFormDesigner/FlatLaf#933]
Occurs as soon as component UI of JRootPane is updates. E.g. when switching theme or when Linux scaling or system font is changed.

caused by fix for #907; commit d471f08b156aef5c2a219d3842465419f516e8d0

~~~
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JComponent.setBounds(int, int, int, int)" because "this.centerComp" is null
	at com.formdev.flatlaf.ui.FlatWindowResizer$WindowResizer.doLayout(FlatWindowResizer.java:275)
	at com.formdev.flatlaf.ui.FlatWindowResizer.updateVisibility(FlatWindowResizer.java:176)
	at com.formdev.flatlaf.ui.FlatWindowResizer.addNotify(FlatWindowResizer.java:155)
	at com.formdev.flatlaf.ui.FlatWindowResizer$WindowResizer.addNotify(FlatWindowResizer.java:287)
	at com.formdev.flatlaf.ui.FlatWindowResizer.<init>(FlatWindowResizer.java:96)
	at com.formdev.flatlaf.ui.FlatWindowResizer$WindowResizer.<init>(FlatWindowResizer.java:242)
	at com.formdev.flatlaf.ui.FlatRootPaneUI.createWindowResizer(FlatRootPaneUI.java:263)
	at com.formdev.flatlaf.ui.FlatRootPaneUI.installClientDecorations(FlatRootPaneUI.java:235)
	at com.formdev.flatlaf.ui.FlatRootPaneUI.installUI(FlatRootPaneUI.java:102)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
	at java.desktop/javax.swing.JRootPane.setUI(JRootPane.java:445)
	at java.desktop/javax.swing.JRootPane.updateUI(JRootPane.java:455)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
	at com.formdev.flatlaf.FlatLaf.updateUI(FlatLaf.java:1092)
	at com.formdev.flatlaf.FlatLaf.lambda$7(FlatLaf.java:1079)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
~~~

**Comment by DevCharly** [comment]
fixed in FlatLaf 3.5.4
